### ISSUE TITLE
CRIANDO E UTILIZANDO O MODEL #04 - Problema no getAll()

### ISSUE THREAD

**Issue by aclimarin** [adrianoluisalmeida/apicars#2]
Estou seguindo seu tutorial e estou no vídeo 04 (https://tinyurl.com/y49gmnte).

Consegui fazer a persistência, porém não estou conseguindo consultar. Não aparece nenhuma mensagem de erro, apenas não busca nada. Já verifiquei na base e o registro está lá.

Veja meu controller (troquei 'cars' por 'atendimento').

Controller
```
public function getAll()
    {
        $agendamentos = $this->model->all();
        response()->json($agendamentos);
    }
```

Rota

`$router->get("api/agendamento", "AgendamentoController@getAll");`

**Comment by aclimarin** [comment]
Eu percebi que esqueci o return haha

**Comment by adrianoluisalmeida** [comment]
@aclimarin Que bom que conseguiu resolver :)
